name: 渲染drawio文件为svg图片
# 描述：每次push源码到master分支后，自动渲染根目录下drawio文件为svg图片

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths-ignore:  # 下列文件的变更不触发
      - '.github/**'
      - '**.md'  # **: Matches zero or more of any character.当然也包括“/”符号，即递归匹配
      - LICENSE
      - .gitattributes

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "render_drawio"
  render_drawio:
    name: job1:自动渲染drawio文件为svg图片
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 01.检出代码
        uses: actions/checkout@v2

      - name: 02.渲染*.drawio文件
        id: render
        uses: docker://ghcr.io/racklet/render-drawio-action:v1
        with: # Showcasing the default values here
          formats: 'svg'
          sub-dirs: '.'
          skip-dirs: '.git'
          # files: '' # unset, specify `dest-file=src-file` mappings here
          log-level: 'info'

      - name: 03.列出已渲染的文件
        run: 'ls -l ${{ steps.render.outputs.rendered-files }}'

      - name: 04.提交渲染出的文件
        uses: EndBug/add-and-commit@v7
        with:
          # This makes the GH Actions user/bot the author of the commit
          default_author: github_actor
          message: 'Automatically render .drawio files'
          add: "${{ steps.render.outputs.rendered-files }}"
        if: "${{ steps.render.outputs.rendered-files != ''}}"
